services:
  cdn:
    image: caddy:2-alpine
    container_name: r4men.com-cdn
    restart: unless-stopped
    ports:
      - "${CDN_PORT}:80"
    volumes:
      - ${CDN_PATH}:/srv:ro
      - ./Caddyfile:/etc/caddy/Caddyfile:ro